Class {
	#name : 'CavWindowStrategy',
	#superclass : 'Object',
	#instVars : [
		'placeHolder'
	],
	#category : 'myBecher-WindowProfile',
	#package : 'myBecher-WindowProfile'
}

{ #category : 'accessing' }
CavWindowStrategy >> placeHolder [

	^ placeHolder
]

{ #category : 'accessing' }
CavWindowStrategy >> placeHolder: anObject [

	placeHolder := anObject
]

{ #category : 'positioning' }
CavWindowStrategy >> placeWindow: aWindowPresenter [
]
