"
I scan the current window and build a profile from the presenters or tools inside them. 
A profile is set of WindowConfigurations.
A WindowConfiguration is a description of the window on the screen (extent, position, kind, strategy)

"
Class {
	#name : 'WindowProfilor',
	#superclass : 'Object',
	#instVars : [
		'profiles',
		'classToolMapping'
	],
	#category : 'myBecher-WindowProfile',
	#package : 'myBecher-WindowProfile'
}
